#banco de dados
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.url=jdbc:postgresql://postgres_db:5432/docker_db
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=user_name
spring.datasource.password=password
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update

#log
management.endpoints.web.exposure.include=loggers
management.endpoint.loggers.enabled=true
logging.config=file:logback.xml